/**
 * Database Seeding Script
 * Run with: npm run seed
 */

import path from 'path';
import dotenv from 'dotenv';
// Load env from .env.local first, then fallback to .env
dotenv.config({ path: path.resolve(process.cwd(), '.env.local'), override: true });
if (!process.env.MONGODB_URI) {
  dotenv.config({ path: path.resolve(process.cwd(), '.env'), override: true });
}

// IMPORTANT: Do not import DB modules before dotenv loads.
// We'll dynamically import them inside seed() after env is ready.

const sampleRecipes = [
  {
    title: 'Paneer Butter Masala',
    description: 'Rich and creamy curry made with paneer cubes in a spiced tomato gravy.',
    imageUrl: 'https://images.unsplash.com/photo-1626778876967-30c1c45df39b?w=800',
    cookTime: 25,
    prepTime: 15,
    servings: 4,
    difficulty: 'Medium',
    ingredients: [
      { name: 'paneer', amount: 250, unit: 'g', category: 'Proteins' },
      { name: 'tomatoes', amount: 3, unit: 'whole', category: 'Vegetables' },
      { name: 'onion', amount: 1, unit: 'whole', category: 'Vegetables' },
      { name: 'butter', amount: 2, unit: 'tbsp', category: 'Oils & Fats' },
      { name: 'cream', amount: 3, unit: 'tbsp', category: 'Dairy' },
      { name: 'garam masala', amount: 1, unit: 'tsp', category: 'Spices & Herbs' },
      { name: 'ginger garlic paste', amount: 1, unit: 'tbsp', category: 'Condiments' },
    ],
    instructions: [
      'Sauté onions and ginger-garlic paste in butter until golden.',
      'Add chopped tomatoes and cook until soft.',
      'Blend the mixture to a smooth paste.',
      'Return to pan, add spices, salt, and cream.',
      'Add paneer cubes, simmer for 5 minutes.',
      'Serve hot with naan or rice.',
    ],
    nutrition: { calories: 420, protein: 18, carbs: 20, fat: 30, fiber: 3, sodium: 300 },
    tags: ['indian', 'vegetarian', 'curry', 'dinner'],
    dietary: { vegetarian: true, vegan: false, glutenFree: true, dairyFree: false, nutFree: true, keto: false, paleo: false },
  },
  {
    title: 'Chole Masala',
    description: 'Spicy North Indian chickpea curry cooked with aromatic spices.',
    imageUrl: 'https://images.unsplash.com/photo-1668236543092-307c7342a3ff?w=800',
    cookTime: 30,
    prepTime: 10,
    servings: 4,
    difficulty: 'Medium',
    ingredients: [
      { name: 'chickpeas', amount: 2, unit: 'cups', category: 'Proteins' },
      { name: 'onion', amount: 2, unit: 'whole', category: 'Vegetables' },
      { name: 'tomatoes', amount: 2, unit: 'whole', category: 'Vegetables' },
      { name: 'chole masala', amount: 2, unit: 'tbsp', category: 'Spices & Herbs' },
      { name: 'ginger garlic paste', amount: 1, unit: 'tbsp', category: 'Condiments' },
    ],
    instructions: [
      'Pressure cook chickpeas until soft.',
      'Sauté onions and ginger-garlic paste until golden.',
      'Add tomatoes and cook till mushy.',
      'Add chole masala and salt, cook for 5 minutes.',
      'Add chickpeas and simmer 10 minutes.',
      'Garnish with coriander and serve with bhature or rice.',
    ],
    nutrition: { calories: 350, protein: 14, carbs: 40, fat: 12, fiber: 10, sodium: 400 },
    tags: ['indian', 'vegan', 'spicy', 'lunch'],
    dietary: { vegetarian: true, vegan: true, glutenFree: true, dairyFree: true, nutFree: true, keto: false, paleo: false },
  },
  {
    title: 'Masala Dosa',
    description: 'Crispy South Indian crepe filled with spicy mashed potatoes.',
    imageUrl: 'https://images.unsplash.com/photo-1630732490567-196f68945f02?w=800',
    cookTime: 20,
    prepTime: 15,
    servings: 3,
    difficulty: 'Medium',
    ingredients: [
      { name: 'dosa batter', amount: 2, unit: 'cups', category: 'Grains' },
      { name: 'potatoes', amount: 3, unit: 'whole', category: 'Vegetables' },
      { name: 'onion', amount: 1, unit: 'whole', category: 'Vegetables' },
      { name: 'mustard seeds', amount: 1, unit: 'tsp', category: 'Spices & Herbs' },
      { name: 'turmeric', amount: 0.5, unit: 'tsp', category: 'Spices & Herbs' },
    ],
    instructions: [
      'Boil and mash potatoes.',
      'Sauté onions and spices, then add mashed potatoes.',
      'Spread dosa batter on hot tawa, drizzle oil.',
      'Add filling and fold the dosa.',
      'Serve hot with chutney and sambar.',
    ],
    nutrition: { calories: 310, protein: 8, carbs: 45, fat: 10, fiber: 4, sodium: 280 },
    tags: ['indian', 'south-indian', 'breakfast', 'vegetarian'],
    dietary: { vegetarian: true, vegan: true, glutenFree: false, dairyFree: true, nutFree: true, keto: false, paleo: false },
  },
  {
    title: 'Dal Tadka',
    description: 'Lentils cooked and tempered with ghee, garlic, and spices.',
    imageUrl: 'https://images.unsplash.com/photo-1630608445444-fdbc2aa2e01b?w=800',
    cookTime: 25,
    prepTime: 10,
    servings: 4,
    difficulty: 'Easy',
    ingredients: [
      { name: 'toor dal', amount: 1, unit: 'cup', category: 'Proteins' },
      { name: 'onion', amount: 1, unit: 'whole', category: 'Vegetables' },
      { name: 'tomato', amount: 1, unit: 'whole', category: 'Vegetables' },
      { name: 'ghee', amount: 2, unit: 'tbsp', category: 'Oils & Fats' },
      { name: 'garlic', amount: 4, unit: 'cloves', category: 'Vegetables' },
      { name: 'red chili powder', amount: 1, unit: 'tsp', category: 'Spices & Herbs' },
    ],
    instructions: [
      'Boil dal with turmeric and salt until soft.',
      'Mash dal and set aside.',
      'In ghee, sauté garlic and spices.',
      'Pour tempering over dal and mix well.',
      'Serve hot with steamed rice.',
    ],
    nutrition: { calories: 280, protein: 12, carbs: 30, fat: 10, fiber: 6, sodium: 200 },
    tags: ['indian', 'vegetarian', 'comfort-food'],
    dietary: { vegetarian: true, vegan: false, glutenFree: true, dairyFree: false, nutFree: true, keto: false, paleo: false },
  },
  {
    title: 'Palak Paneer',
    description: 'Spinach gravy blended with paneer cubes and mild spices.',
    imageUrl: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6e8eb?w=800',
    cookTime: 20,
    prepTime: 10,
    servings: 3,
    difficulty: 'Medium',
    ingredients: [
      { name: 'spinach', amount: 3, unit: 'cups', category: 'Vegetables' },
      { name: 'paneer', amount: 200, unit: 'g', category: 'Proteins' },
      { name: 'onion', amount: 1, unit: 'whole', category: 'Vegetables' },
      { name: 'ginger garlic paste', amount: 1, unit: 'tbsp', category: 'Condiments' },
      { name: 'cream', amount: 2, unit: 'tbsp', category: 'Dairy' },
    ],
    instructions: [
      'Blanch spinach and blend to a smooth paste.',
      'Sauté onions and ginger garlic paste.',
      'Add spinach puree, salt, and spices.',
      'Stir in cream and paneer cubes.',
      'Simmer 5 minutes and serve with roti or rice.',
    ],
    nutrition: { calories: 310, protein: 16, carbs: 15, fat: 22, fiber: 4, sodium: 250 },
    tags: ['indian', 'vegetarian', 'healthy', 'curry'],
    dietary: { vegetarian: true, vegan: false, glutenFree: true, dairyFree: false, nutFree: true, keto: false, paleo: false },
  },
  {
    title: 'Aloo Gobi',
    description: 'A classic North Indian dry curry with potatoes and cauliflower.',
    imageUrl: 'https://images.unsplash.com/photo-1600788907416-8ecac9e3db31?w=800',
    cookTime: 20,
    prepTime: 10,
    servings: 3,
    difficulty: 'Easy',
    ingredients: [
      { name: 'potatoes', amount: 2, unit: 'whole', category: 'Vegetables' },
      { name: 'cauliflower', amount: 1, unit: 'small', category: 'Vegetables' },
      { name: 'turmeric', amount: 0.5, unit: 'tsp', category: 'Spices & Herbs' },
      { name: 'cumin seeds', amount: 1, unit: 'tsp', category: 'Spices & Herbs' },
      { name: 'garam masala', amount: 1, unit: 'tsp', category: 'Spices & Herbs' },
    ],
    instructions: [
      'Heat oil, add cumin seeds and let them splutter.',
      'Add potatoes and cauliflower, mix well.',
      'Add spices and a splash of water.',
      'Cook covered until tender.',
      'Garnish with coriander and serve.',
    ],
    nutrition: { calories: 210, protein: 6, carbs: 30, fat: 8, fiber: 5, sodium: 180 },
    tags: ['indian', 'vegan', 'vegetarian', 'lunch'],
    dietary: { vegetarian: true, vegan: true, glutenFree: true, dairyFree: true, nutFree: true, keto: false, paleo: false },
  },
  {
    title: 'Butter Chicken',
    description: 'Tender chicken pieces cooked in a creamy tomato-based sauce.',
    imageUrl: 'https://images.unsplash.com/photo-1600628422019-347d08e8b1f5?w=800',
    cookTime: 35,
    prepTime: 15,
    servings: 4,
    difficulty: 'Medium',
    ingredients: [
      { name: 'chicken', amount: 500, unit: 'g', category: 'Proteins' },
      { name: 'tomatoes', amount: 3, unit: 'whole', category: 'Vegetables' },
      { name: 'butter', amount: 3, unit: 'tbsp', category: 'Oils & Fats' },
      { name: 'cream', amount: 4, unit: 'tbsp', category: 'Dairy' },
      { name: 'garam masala', amount: 1, unit: 'tsp', category: 'Spices & Herbs' },
    ],
    instructions: [
      'Marinate chicken in yogurt and spices, grill until cooked.',
      'Blend tomatoes and make gravy with butter and cream.',
      'Add grilled chicken and simmer for 10 minutes.',
      'Serve hot with naan or rice.',
    ],
    nutrition: { calories: 480, protein: 35, carbs: 10, fat: 35, fiber: 2, sodium: 400 },
    tags: ['indian', 'non-veg', 'curry', 'dinner'],
    dietary: { vegetarian: false, vegan: false, glutenFree: true, dairyFree: false, nutFree: true, keto: false, paleo: false },
  },
  {
    title: 'Vegetable Biryani',
    description: 'Fragrant rice cooked with mixed vegetables and aromatic spices.',
    imageUrl: 'https://images.unsplash.com/photo-1604908554165-76e63a70a3a1?w=800',
    cookTime: 40,
    prepTime: 15,
    servings: 4,
    difficulty: 'Medium',
    ingredients: [
      { name: 'basmati rice', amount: 2, unit: 'cups', category: 'Grains' },
      { name: 'mixed vegetables', amount: 2, unit: 'cups', category: 'Vegetables' },
      { name: 'yogurt', amount: 0.5, unit: 'cup', category: 'Dairy' },
      { name: 'biryani masala', amount: 2, unit: 'tbsp', category: 'Spices & Herbs' },
      { name: 'saffron', amount: 1, unit: 'pinch', category: 'Spices & Herbs' },
    ],
    instructions: [
      'Parboil rice and drain.',
      'Sauté vegetables and add yogurt and spices.',
      'Layer rice and vegetable mixture alternately in a pot.',
      'Steam on low heat for 15 minutes.',
      'Serve hot with raita.',
    ],
    nutrition: { calories: 380, protein: 9, carbs: 65, fat: 8, fiber: 5, sodium: 350 },
    tags: ['indian', 'biryani', 'vegetarian', 'main-course'],
    dietary: { vegetarian: true, vegan: false, glutenFree: true, dairyFree: false, nutFree: true, keto: false, paleo: false },
  },
  {
    title: 'Rasgulla',
    description: 'Soft spongy balls made from chenna soaked in sugar syrup.',
    imageUrl: 'https://images.unsplash.com/photo-1653407741538-9690a2e6e93d?w=800',
    cookTime: 30,
    prepTime: 15,
    servings: 6,
    difficulty: 'Hard',
    ingredients: [
      { name: 'milk', amount: 1, unit: 'liter', category: 'Dairy' },
      { name: 'lemon juice', amount: 2, unit: 'tbsp', category: 'Condiments' },
      { name: 'sugar', amount: 1, unit: 'cup', category: 'Sweeteners' },
      { name: 'water', amount: 3, unit: 'cups', category: 'Other' },
    ],
    instructions: [
      'Boil milk and curdle with lemon juice.',
      'Strain chenna and knead into smooth dough.',
      'Shape into small balls.',
      'Boil sugar syrup and add chenna balls.',
      'Cook 10 minutes and let cool in syrup.',
    ],
    nutrition: { calories: 180, protein: 6, carbs: 25, fat: 6, fiber: 0, sodium: 60 },
    tags: ['indian', 'dessert', 'sweet'],
    dietary: { vegetarian: true, vegan: false, glutenFree: true, dairyFree: false, nutFree: true, keto: false, paleo: false },
  },
  {
    title: 'Poha',
    description: 'Light Indian breakfast made with flattened rice and spices.',
    imageUrl: 'https://images.unsplash.com/photo-1646653540532-8c9b4a899d44?w=800',
    cookTime: 10,
    prepTime: 10,
    servings: 2,
    difficulty: 'Easy',
    ingredients: [
      { name: 'poha (flattened rice)', amount: 1, unit: 'cup', category: 'Grains' },
      { name: 'onion', amount: 1, unit: 'whole', category: 'Vegetables' },
      { name: 'mustard seeds', amount: 0.5, unit: 'tsp', category: 'Spices & Herbs' },
      { name: 'turmeric', amount: 0.25, unit: 'tsp', category: 'Spices & Herbs' },
      { name: 'lemon juice', amount: 1, unit: 'tbsp', category: 'Condiments' },
    ],
    instructions: [
      'Rinse poha and drain water.',
      'Heat oil, add mustard seeds and onions.',
      'Add turmeric, salt, and poha.',
      'Stir well and cook for 3 minutes.',
      'Add lemon juice and serve hot.',
    ],
    nutrition: { calories: 250, protein: 6, carbs: 45, fat: 5, fiber: 3, sodium: 180 },
    tags: ['indian', 'breakfast', 'light', 'vegetarian'],
    dietary: { vegetarian: true, vegan: true, glutenFree: true, dairyFree: true, nutFree: true, keto: false, paleo: false },
  },
  {
    title: 'Idli Sambhar',
    description: 'Steamed rice cakes served with spicy lentil soup.',
    imageUrl: 'https://images.unsplash.com/photo-1601042869748-afe88c9c99aa?w=800',
    cookTime: 30,
    prepTime: 15,
    servings: 4,
    difficulty: 'Medium',
    ingredients: [
      { name: 'idli batter', amount: 2, unit: 'cups', category: 'Grains' },
      { name: 'toor dal', amount: 0.5, unit: 'cup', category: 'Proteins' },
      { name: 'tamarind', amount: 1, unit: 'tbsp', category: 'Condiments' },
      { name: 'sambhar powder', amount: 2, unit: 'tbsp', category: 'Spices & Herbs' },
      { name: 'vegetables', amount: 1, unit: 'cup', category: 'Vegetables' },
    ],
    instructions: [
      'Steam idlis in a steamer for 10 minutes.',
      'Cook dal and vegetables with sambhar powder and tamarind.',
      'Serve hot idlis with sambhar and chutney.',
    ],
    nutrition: { calories: 280, protein: 10, carbs: 45, fat: 6, fiber: 4, sodium: 220 },
    tags: ['indian', 'south-indian', 'breakfast', 'vegetarian'],
    dietary: { vegetarian: true, vegan: true, glutenFree: false, dairyFree: true, nutFree: true, keto: false, paleo: false },
  },
  {
    title: 'Fish Curry',
    description: 'Spicy and tangy fish curry from coastal India.',
    imageUrl: 'https://images.unsplash.com/photo-1601315486688-5e74263b5b49?w=800',
    cookTime: 30,
    prepTime: 15,
    servings: 4,
    difficulty: 'Medium',
    ingredients: [
      { name: 'fish', amount: 500, unit: 'g', category: 'Proteins' },
      { name: 'coconut milk', amount: 1, unit: 'cup', category: 'Dairy' },
      { name: 'onion', amount: 1, unit: 'whole', category: 'Vegetables' },
      { name: 'tamarind', amount: 1, unit: 'tbsp', category: 'Condiments' },
      { name: 'red chili powder', amount: 1, unit: 'tsp', category: 'Spices & Herbs' },
    ],
    instructions: [
      'Marinate fish with turmeric and salt.',
      'Sauté onions and spices in oil.',
      'Add tamarind and coconut milk.',
      'Simmer fish in sauce until cooked through.',
      'Serve with rice.',
    ],
    nutrition: { calories: 410, protein: 35, carbs: 6, fat: 28, fiber: 2, sodium: 350 },
    tags: ['indian', 'seafood', 'curry', 'dinner'],
    dietary: { vegetarian: false, vegan: false, glutenFree: true, dairyFree: false, nutFree: true, keto: true, paleo: true },
  },
  {
    title: 'Pav Bhaji',
    description: 'Mumbai-style street food made with mashed vegetables and buttered pav.',
    imageUrl: 'https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?w=800',
    cookTime: 25,
    prepTime: 15,
    servings: 3,
    difficulty: 'Easy',
    ingredients: [
      { name: 'mixed vegetables', amount: 2, unit: 'cups', category: 'Vegetables' },
      { name: 'pav bhaji masala', amount: 2, unit: 'tbsp', category: 'Spices & Herbs' },
      { name: 'butter', amount: 2, unit: 'tbsp', category: 'Oils & Fats' },
      { name: 'bread rolls', amount: 6, unit: 'pieces', category: 'Grains' },
      { name: 'onion', amount: 1, unit: 'whole', category: 'Vegetables' },
    ],
    instructions: [
      'Boil and mash vegetables.',
      'Sauté onions, add masala and mashed veggies.',
      'Cook with butter until thick.',
      'Toast pav in butter and serve with bhaji.',
    ],
    nutrition: { calories: 450, protein: 10, carbs: 60, fat: 18, fiber: 8, sodium: 300 },
    tags: ['indian', 'street-food', 'vegetarian'],
    dietary: { vegetarian: true, vegan: false, glutenFree: false, dairyFree: false, nutFree: true, keto: false, paleo: false },
  },
  {
    title: 'Rajma Chawal',
    description: 'Kidney bean curry served with steamed basmati rice.',
    imageUrl: 'https://images.unsplash.com/photo-1627308595217-74b9d6e2a52b?w=800',
    cookTime: 35,
    prepTime: 10,
    servings: 3,
    difficulty: 'Medium',
    ingredients: [
      { name: 'rajma (kidney beans)', amount: 1.5, unit: 'cups', category: 'Proteins' },
      { name: 'onion', amount: 1, unit: 'whole', category: 'Vegetables' },
      { name: 'tomatoes', amount: 2, unit: 'whole', category: 'Vegetables' },
      { name: 'ginger garlic paste', amount: 1, unit: 'tbsp', category: 'Condiments' },
      { name: 'rice', amount: 2, unit: 'cups', category: 'Grains' },
    ],
    instructions: [
      'Pressure cook soaked rajma until soft.',
      'Prepare masala with onion, tomatoes, and spices.',
      'Add cooked rajma and simmer 10 minutes.',
      'Serve with steamed rice.',
    ],
    nutrition: { calories: 420, protein: 15, carbs: 70, fat: 8, fiber: 12, sodium: 300 },
    tags: ['indian', 'vegetarian', 'curry', 'comfort-food'],
    dietary: { vegetarian: true, vegan: true, glutenFree: true, dairyFree: true, nutFree: true, keto: false, paleo: false },
  },
  {
    title: 'Chicken Biryani',
    description: 'Aromatic rice dish layered with spicy chicken curry.',
    imageUrl: 'https://images.unsplash.com/photo-1598514982901-f43b7a1f8cda?w=800',
    cookTime: 45,
    prepTime: 20,
    servings: 4,
    difficulty: 'Hard',
    ingredients: [
      { name: 'chicken', amount: 500, unit: 'g', category: 'Proteins' },
      { name: 'basmati rice', amount: 2, unit: 'cups', category: 'Grains' },
      { name: 'yogurt', amount: 0.5, unit: 'cup', category: 'Dairy' },
      { name: 'biryani masala', amount: 2, unit: 'tbsp', category: 'Spices & Herbs' },
      { name: 'onions', amount: 2, unit: 'whole', category: 'Vegetables' },
    ],
    instructions: [
      'Marinate chicken with yogurt and spices.',
      'Cook onions until golden brown.',
      'Layer rice and chicken alternately.',
      'Steam on low for 15 minutes.',
      'Serve hot with raita.',
    ],
    nutrition: { calories: 520, protein: 32, carbs: 50, fat: 20, fiber: 4, sodium: 400 },
    tags: ['indian', 'non-veg', 'biryani', 'dinner'],
    dietary: { vegetarian: false, vegan: false, glutenFree: true, dairyFree: false, nutFree: true, keto: false, paleo: false },
  },
  {
    title: 'Matar Paneer',
    description: 'Paneer cubes cooked with peas in a tomato-based curry.',
    imageUrl: 'https://images.unsplash.com/photo-1626773979354-b093d6f7fcd0?w=800',
    cookTime: 25,
    prepTime: 10,
    servings: 3,
    difficulty: 'Easy',
    ingredients: [
      { name: 'paneer', amount: 200, unit: 'g', category: 'Proteins' },
      { name: 'peas', amount: 1, unit: 'cup', category: 'Vegetables' },
      { name: 'tomatoes', amount: 2, unit: 'whole', category: 'Vegetables' },
      { name: 'onion', amount: 1, unit: 'whole', category: 'Vegetables' },
      { name: 'garam masala', amount: 1, unit: 'tsp', category: 'Spices & Herbs' },
    ],
    instructions: [
      'Sauté onions and tomatoes until soft.',
      'Add spices and cook gravy.',
      'Add peas and paneer cubes.',
      'Simmer for 10 minutes and serve.',
    ],
    nutrition: { calories: 330, protein: 16, carbs: 20, fat: 22, fiber: 5, sodium: 280 },
    tags: ['indian', 'vegetarian', 'curry', 'dinner'],
    dietary: { vegetarian: true, vegan: false, glutenFree: true, dairyFree: false, nutFree: true, keto: false, paleo: false },
  },
  {
    title: 'Kadai Chicken',
    description: 'Spicy chicken cooked with bell peppers and kadai masala.',
    imageUrl: 'https://images.unsplash.com/photo-1626808642875-0aa545482dfb?w=800',
    cookTime: 35,
    prepTime: 15,
    servings: 4,
    difficulty: 'Medium',
    ingredients: [
      { name: 'chicken', amount: 500, unit: 'g', category: 'Proteins' },
      { name: 'bell peppers', amount: 2, unit: 'whole', category: 'Vegetables' },
      { name: 'onions', amount: 2, unit: 'whole', category: 'Vegetables' },
      { name: 'kadai masala', amount: 2, unit: 'tbsp', category: 'Spices & Herbs' },
      { name: 'tomatoes', amount: 2, unit: 'whole', category: 'Vegetables' },
    ],
    instructions: [
      'Sauté onions and tomatoes to make masala base.',
      'Add chicken and spices, cook until tender.',
      'Add diced bell peppers and cook 5 minutes.',
      'Serve hot with naan.',
    ],
    nutrition: { calories: 450, protein: 35, carbs: 10, fat: 30, fiber: 3, sodium: 400 },
    tags: ['indian', 'non-veg', 'spicy', 'curry'],
    dietary: { vegetarian: false, vegan: false, glutenFree: true, dairyFree: true, nutFree: true, keto: true, paleo: true },
  },
  {
    title: 'Gulab Jamun',
    description: 'Soft fried dough balls soaked in sugar syrup.',
    imageUrl: 'https://images.unsplash.com/photo-1627194060360-89a7df0040c5?w=800',
    cookTime: 30,
    prepTime: 15,
    servings: 6,
    difficulty: 'Medium',
    ingredients: [
      { name: 'milk powder', amount: 1, unit: 'cup', category: 'Dairy' },
      { name: 'flour', amount: 0.25, unit: 'cup', category: 'Grains' },
      { name: 'ghee', amount: 2, unit: 'tbsp', category: 'Oils & Fats' },
      { name: 'sugar', amount: 1, unit: 'cup', category: 'Sweeteners' },
      { name: 'cardamom', amount: 1, unit: 'tsp', category: 'Spices & Herbs' },
    ],
    instructions: [
      'Mix milk powder, flour, and ghee into soft dough.',
      'Shape into balls and deep fry on low heat.',
      'Prepare sugar syrup with cardamom.',
      'Soak fried balls in syrup for 30 minutes.',
    ],
    nutrition: { calories: 220, protein: 4, carbs: 30, fat: 10, fiber: 1, sodium: 80 },
    tags: ['indian', 'dessert', 'sweet'],
    dietary: { vegetarian: true, vegan: false, glutenFree: false, dairyFree: false, nutFree: true, keto: false, paleo: false },
  },
  {
    title: 'Pulao',
    description: 'Fragrant rice cooked with vegetables and mild spices.',
    imageUrl: 'https://images.unsplash.com/photo-1603368163749-83a0a5d5bb4c?w=800',
    cookTime: 25,
    prepTime: 10,
    servings: 4,
    difficulty: 'Easy',
    ingredients: [
      { name: 'basmati rice', amount: 2, unit: 'cups', category: 'Grains' },
      { name: 'mixed vegetables', amount: 2, unit: 'cups', category: 'Vegetables' },
      { name: 'ghee', amount: 2, unit: 'tbsp', category: 'Oils & Fats' },
      { name: 'garam masala', amount: 1, unit: 'tsp', category: 'Spices & Herbs' },
      { name: 'bay leaf', amount: 1, unit: 'whole', category: 'Spices & Herbs' },
    ],
    instructions: [
      'Sauté spices and vegetables in ghee.',
      'Add soaked rice and water.',
      'Cook covered until rice is done.',
      'Fluff and serve with raita.',
    ],
    nutrition: { calories: 340, protein: 8, carbs: 60, fat: 8, fiber: 4, sodium: 250 },
    tags: ['indian', 'vegetarian', 'rice', 'lunch'],
    dietary: { vegetarian: true, vegan: false, glutenFree: true, dairyFree: false, nutFree: true, keto: false, paleo: false },
  },
  {
    title: 'Pani Puri',
    description: 'Crispy puris filled with tangy, spicy water and potato filling.',
    imageUrl: 'https://images.unsplash.com/photo-1638176063669-9f926967b26b?w=800',
    cookTime: 20,
    prepTime: 20,
    servings: 5,
    difficulty: 'Hard',
    ingredients: [
      { name: 'puri', amount: 30, unit: 'pieces', category: 'Grains' },
      { name: 'potatoes', amount: 3, unit: 'whole', category: 'Vegetables' },
      { name: 'tamarind', amount: 2, unit: 'tbsp', category: 'Condiments' },
      { name: 'mint leaves', amount: 0.5, unit: 'cup', category: 'Vegetables' },
      { name: 'spices', amount: 1, unit: 'tbsp', category: 'Spices & Herbs' },
    ],
    instructions: [
      'Boil and mash potatoes with spices.',
      'Blend tamarind, mint, and spices for flavored water.',
      'Crack puris, fill with potatoes, and pour pani.',
    ],
    nutrition: { calories: 200, protein: 5, carbs: 35, fat: 6, fiber: 3, sodium: 250 },
    tags: ['indian', 'street-food', 'snack', 'vegan'],
    dietary: { vegetarian: true, vegan: true, glutenFree: false, dairyFree: true, nutFree: true, keto: false, paleo: false },
  },
  {
    title: 'Samosa',
    description: 'Crispy pastry filled with spiced potatoes and peas.',
    imageUrl: 'https://images.unsplash.com/photo-1605090823009-7a5ba3a0aef4?w=800',
    cookTime: 30,
    prepTime: 15,
    servings: 6,
    difficulty: 'Hard',
    ingredients: [
      { name: 'flour', amount: 2, unit: 'cups', category: 'Grains' },
      { name: 'potatoes', amount: 3, unit: 'whole', category: 'Vegetables' },
      { name: 'peas', amount: 0.5, unit: 'cup', category: 'Vegetables' },
      { name: 'cumin seeds', amount: 1, unit: 'tsp', category: 'Spices & Herbs' },
      { name: 'oil', amount: 2, unit: 'tbsp', category: 'Oils & Fats' },
    ],
    instructions: [
      'Make dough with flour and oil.',
      'Prepare potato-pea filling with spices.',
      'Stuff and shape samosas, deep fry until golden.',
    ],
    nutrition: { calories: 260, protein: 6, carbs: 30, fat: 12, fiber: 4, sodium: 200 },
    tags: ['indian', 'snack', 'street-food', 'vegetarian'],
    dietary: { vegetarian: true, vegan: true, glutenFree: false, dairyFree: true, nutFree: true, keto: false, paleo: false },
  },
  {
    title: 'Classic Spaghetti Carbonara',
    description: 'A traditional Italian pasta dish with eggs, cheese, bacon, and black pepper.',
    imageUrl: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800',
    cookTime: 20,
    prepTime: 10,
    servings: 4,
    difficulty: 'Medium',
    ingredients: [
      { name: 'spaghetti', amount: 400, unit: 'g', category: 'Grains' },
      { name: 'bacon', amount: 200, unit: 'g', category: 'Proteins' },
      { name: 'eggs', amount: 4, unit: 'whole', category: 'Dairy' },
      { name: 'parmesan cheese', amount: 100, unit: 'g', category: 'Dairy' },
      { name: 'black pepper', amount: 1, unit: 'tsp', category: 'Spices & Herbs' },
    ],
    instructions: [
      'Cook spaghetti according to package directions in salted boiling water.',
      'Meanwhile, fry bacon in a large pan until crispy.',
      'In a bowl, whisk together eggs, grated parmesan, and black pepper.',
      'Drain pasta, reserving 1 cup of pasta water.',
      'Add hot pasta to the pan with bacon, remove from heat.',
      'Quickly stir in egg mixture, adding pasta water to create a creamy sauce.',
      'Serve immediately with extra parmesan and black pepper.',
    ],
    nutrition: {
      calories: 650,
      protein: 28,
      carbs: 75,
      fat: 25,
      fiber: 3,
      sodium: 450,
    },
    tags: ['pasta', 'italian', 'quick', 'dinner'],
    dietary: {
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      dairyFree: false,
      nutFree: true,
      keto: false,
      paleo: false,
    },
  },
  {
    title: 'Buddha Bowl with Quinoa',
    description: 'A colorful, nutrient-packed bowl with quinoa, roasted vegetables, and tahini dressing.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
    cookTime: 25,
    prepTime: 15,
    servings: 2,
    difficulty: 'Easy',
    ingredients: [
      { name: 'quinoa', amount: 1, unit: 'cup', category: 'Grains' },
      { name: 'sweet potato', amount: 1, unit: 'large', category: 'Vegetables' },
      { name: 'chickpeas', amount: 400, unit: 'g', category: 'Proteins' },
      { name: 'kale', amount: 2, unit: 'cups', category: 'Vegetables' },
      { name: 'avocado', amount: 1, unit: 'whole', category: 'Vegetables' },
      { name: 'tahini', amount: 3, unit: 'tbsp', category: 'Condiments' },
      { name: 'lemon juice', amount: 2, unit: 'tbsp', category: 'Condiments' },
    ],
    instructions: [
      'Preheat oven to 400°F (200°C).',
      'Cook quinoa according to package instructions.',
      'Cube sweet potato and toss with olive oil, salt, and pepper. Roast for 25 minutes.',
      'Drain and roast chickpeas until crispy.',
      'Massage kale with a bit of olive oil.',
      'Make tahini dressing by mixing tahini, lemon juice, and water until smooth.',
      'Assemble bowls with quinoa, roasted vegetables, chickpeas, kale, sliced avocado, and drizzle with tahini dressing.',
    ],
    nutrition: {
      calories: 520,
      protein: 18,
      carbs: 68,
      fat: 20,
      fiber: 15,
      sodium: 180,
    },
    tags: ['healthy', 'vegan', 'bowl', 'lunch'],
    dietary: {
      vegetarian: true,
      vegan: true,
      glutenFree: true,
      dairyFree: true,
      nutFree: false,
      keto: false,
      paleo: false,
    },
  },
  {
    title: 'Grilled Chicken Salad',
    description: 'Fresh greens topped with juicy grilled chicken and a zesty vinaigrette.',
    imageUrl: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800',
    cookTime: 15,
    prepTime: 10,
    servings: 2,
    difficulty: 'Easy',
    ingredients: [
      { name: 'chicken breast', amount: 300, unit: 'g', category: 'Proteins' },
      { name: 'mixed greens', amount: 4, unit: 'cups', category: 'Vegetables' },
      { name: 'cherry tomatoes', amount: 1, unit: 'cup', category: 'Vegetables' },
      { name: 'cucumber', amount: 1, unit: 'whole', category: 'Vegetables' },
      { name: 'olive oil', amount: 3, unit: 'tbsp', category: 'Oils & Fats' },
      { name: 'balsamic vinegar', amount: 2, unit: 'tbsp', category: 'Condiments' },
    ],
    instructions: [
      'Season chicken breast with salt, pepper, and herbs.',
      'Grill chicken for 6-7 minutes per side until cooked through.',
      'Let chicken rest for 5 minutes, then slice.',
      'Prepare salad with mixed greens, halved cherry tomatoes, and sliced cucumber.',
      'Make dressing by whisking olive oil, balsamic vinegar, salt, and pepper.',
      'Top salad with sliced chicken and drizzle with dressing.',
    ],
    nutrition: {
      calories: 380,
      protein: 42,
      carbs: 12,
      fat: 18,
      fiber: 4,
      sodium: 220,
    },
    tags: ['salad', 'healthy', 'protein', 'low-carb'],
    dietary: {
      vegetarian: false,
      vegan: false,
      glutenFree: true,
      dairyFree: true,
      nutFree: true,
      keto: true,
      paleo: true,
    },
  },
  {
    title: 'Vegetable Stir Fry',
    description: 'Quick and colorful stir-fried vegetables with a savory Asian-inspired sauce.',
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800',
    cookTime: 12,
    prepTime: 15,
    servings: 3,
    difficulty: 'Easy',
    ingredients: [
      { name: 'broccoli', amount: 2, unit: 'cups', category: 'Vegetables' },
      { name: 'bell peppers', amount: 2, unit: 'whole', category: 'Vegetables' },
      { name: 'carrots', amount: 2, unit: 'whole', category: 'Vegetables' },
      { name: 'garlic', amount: 3, unit: 'cloves', category: 'Vegetables' },
      { name: 'ginger', amount: 1, unit: 'tbsp', category: 'Spices & Herbs' },
      { name: 'soy sauce', amount: 3, unit: 'tbsp', category: 'Condiments' },
      { name: 'sesame oil', amount: 1, unit: 'tbsp', category: 'Oils & Fats' },
    ],
    instructions: [
      'Cut all vegetables into bite-sized pieces.',
      'Heat sesame oil in a large wok or pan over high heat.',
      'Add minced garlic and ginger, stir fry for 30 seconds.',
      'Add harder vegetables (carrots, broccoli) first, stir fry for 3 minutes.',
      'Add bell peppers and continue cooking for 2 minutes.',
      'Add soy sauce and a splash of water, toss everything together.',
      'Cook until vegetables are tender-crisp, about 2 more minutes.',
      'Serve hot over rice or noodles.',
    ],
    nutrition: {
      calories: 180,
      protein: 6,
      carbs: 24,
      fat: 8,
      fiber: 6,
      sodium: 720,
    },
    tags: ['vegan', 'quick', 'asian', 'side-dish'],
    dietary: {
      vegetarian: true,
      vegan: true,
      glutenFree: false,
      dairyFree: true,
      nutFree: true,
      keto: false,
      paleo: false,
    },
  },
];

const sampleIngredients = [
  {
    name: 'chicken breast',
    category: 'Proteins',
    commonUnits: ['g', 'oz', 'whole'],
    aliases: ['chicken', 'chicken fillet'],
    nutritionPer100g: {
      calories: 165,
      protein: 31,
      carbs: 0,
      fat: 3.6,
      fiber: 0,
    },
    dietaryInfo: {
      vegetarian: false,
      vegan: false,
      glutenFree: true,
      dairyFree: true,
      nutFree: true,
    },
  },
  {
    name: 'quinoa',
    category: 'Grains',
    commonUnits: ['cup', 'g'],
    aliases: ['quinoa grain'],
    nutritionPer100g: {
      calories: 120,
      protein: 4.4,
      carbs: 21,
      fat: 1.9,
      fiber: 2.8,
    },
    dietaryInfo: {
      vegetarian: true,
      vegan: true,
      glutenFree: true,
      dairyFree: true,
      nutFree: true,
    },
  },
  {
    name: 'tomato',
    category: 'Vegetables',
    commonUnits: ['whole', 'cup', 'g'],
    aliases: ['tomatoes', 'cherry tomatoes'],
    nutritionPer100g: {
      calories: 18,
      protein: 0.9,
      carbs: 3.9,
      fat: 0.2,
      fiber: 1.2,
    },
    dietaryInfo: {
      vegetarian: true,
      vegan: true,
      glutenFree: true,
      dairyFree: true,
      nutFree: true,
    },
  },
];

async function seed() {
  try {
    console.log('🌱 Starting database seed...');
    // Dynamically import DB and models AFTER dotenv has populated env vars
    const { default: connectDB } = await import('../lib/mongodb');
    const { default: Recipe } = await import('../models/Recipe');
    const { default: IngredientMetadata } = await import('../models/Ingredient');

    await connectDB();
    console.log('✅ Connected to MongoDB');

    // Clear existing data
    await Recipe.deleteMany({});
    await IngredientMetadata.deleteMany({});
    console.log('🗑️  Cleared existing data');

    // Insert sample data
    const insertedRecipes = await Recipe.insertMany(sampleRecipes);
    console.log(`✅ Inserted ${insertedRecipes.length} recipes`);

    const insertedIngredients = await IngredientMetadata.insertMany(sampleIngredients);
    console.log(`✅ Inserted ${insertedIngredients.length} ingredient metadata entries`);

    console.log('🎉 Database seeding completed successfully!');
    console.log('\nSample recipes:');
    insertedRecipes.forEach((recipe) => {
      console.log(`  - ${recipe.title} (${recipe.difficulty})`);
    });

    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  }
}

seed();

